#########################
audio_input_file:
    input_stream:
        sample_rate: 44100
        chunk_size: 1024
        flush_duration: 10 # for flushing after file completes
    topics:
        input:
            filepath: 'input/filepath'
        output:
            audio: 'input/audio'        #auto_shepherd_msgs/AudioChunk

#########################
audio_input_mic:
    input_stream:
        sample_delay: 50 #ms #TODO
        sample_rate: 44100 #2x the max Hz detected
        chunk_size: 1024 #total Hz bins in capture
    topics:
        output:
            audio: 'input/audio'        #auto_shepherd_msgs/AudioChunk

#########################
audio_preprocessor:
    spectrogram:
        window_duration: 10 #total time to batch into image
    preprocessing:
        threshold_db: 0 #-10
        medfilt:
          do: True
          kernel: 3
        normalize:
          do: True
          min: -10
          max: 55
        frequency_crop:
          do: False
          min: 50
          max: 5000
        secondary_threshold_db: 0 #-5
    topics:
        input:
            audio: 'input/audio'        #auto_shepherd_msgs/AudioChunk
        output:
            raw: 'preprocessed/raw'     #auto_shepherd_msgs/Spectrogram
        visual:
            st_raw: 'stream/raw_img'       #sensor_msgs/Image
            st_rgb: 'stream/rgb_img'       #sensor_msgs/Image
            pr_raw: 'preprocessed/raw_img' #sensor_msgs/Image
            pr_rgb: 'preprocessed/rgb_img' #sensor_msgs/Image


#########################
codex_detector:
    activity_detection:
        run: False
        record_duration: 1.5
    topics:
        input:
            raw: 'preprocessed/raw'
        output:
            codex: 'codex/pitch_track'
        visual:
            raw: 'codex/raw_img'
            rgb: 'codex/rgb_img'


#########################
template_creator:
    topics:
        input:
            raw: 'stream/raw'
            save: 'template/save'
    samples:
        absolute_dir: ''
        src_directory_filepath:
            package: 'auto_shepherd_whistle_teleop'
            subpath: 'templates_creator/'




#########################
template_matching:
    topics:
        input:
            raw: 'preprocessed/raw'  #auto_shepherd_msgs/Spectrogram
        output:
            raw: 'detected/labels'   #auto_shepherd_msgs/SpectrogramClassification
        visual:
            raw: 'detected/raw_bounds'  #sensor_msgs/Image
            rgb: 'detected/rgb_bounds'  #sensor_msgs/Image
    options:
        input_delay: 1
        draw_style: 'all' #best, group_best, all
    samples:
        absolute_dir: ''
        share_directory_filepath:
            package: 'auto_shepherd_whistle_teleop'
            subpath: 'templates/'
        default_details:
            bounding_box_colour: [255,0,0]
            sensitivity: 0.7
            frequency_search_range:
              min: 50
              max: 5000
            sub_directory: '{action}/'
        details:
#          - action: 'stop'
#            bounding_box_colour: [0,0,255]
#            sub_directory: 'wolf_whistle/'

#          - action: 'forward'
#            bounding_box_colour: [0,255,255]
#            sub_directory: 'good_bad_ugly/'

#          - action: 'backward'
#            bounding_box_colour: [0,255,0]
#            sub_directory: 'hill_slope/'

#          - action: 'right'
#            bounding_box_colour: [255,0,255]
#            sub_directory: 'woody/'

#          - action: 'left'
#            sub_directory: '4_wide_invert_siren/'

#          - action: 'andy_griffith'
#          - action: 'charge'
#          - action: 'double_hill_slope'
          - action: 'good_bad_ugly'
#          - action: 'hill_slope'
#          - action: 'jigglypuff'
#          - action: 'mario'
#          - action: 'N'
#          - action: 'shave_and_a_haircut'
#          - action: 'the_river_kwai_march'
#          - action: 'twisted_nerve'
#          - action: 'wii_fit_obese'
#          - action: 'wolf_whistle'
#          - action: 'woody'
#          - action: 'zelda_item'
#          - action: 'zelda_main_theme'


#########################

mp3_writer:
    input_stream:
        sample_rate: 44100
        chunk_size: 1024
        window_duration: 10
    topics:
        input:
            class: 'labelled/classfied_spectrogram'
    samples:
        absolute_dir: ''
        src_directory_filepath:
            package: 'auto_shepherd_whistle_teleop'
            subpath: 'classified/'
