audio_filter:
    input_stream:
        sample_rate: 44100
        chunk_size: 1024
        window_duration: 5
        threshold_db: -10
        secondary_threshold_db: -5
        animation_interval: 50
        show_display: False
    preprocessing:
        medfilt_kernel: 3
        normalize_min: -10
        normalize_max: 55
        frequency_min: 500
        frequency_max: 5000
    activity_detection:
        run: False
        record_duration: 1.5
    topics:
        input:
            raw: 'stream/raw'
            rgb: 'stream/rgb'
        detector:
            raw: 'detected/raw'
            rgb: 'detected/rgb'
            codex: 'detected/pitch_track'

template_matching:
    topics:
        input:
            raw: 'stream/raw'
        output:
            raw: 'labelled/raw'
            rgb: 'labelled/rgb'
    samples:
        absolute_dir: ''
        share_directory_filepath:
            package: 'auto_shepherd_whistle_teleop'
            subpath: 'templates/'
        details:
          - action: 'stop'
            bounding_box_colour: [0,0,255]
            sensitivity: 0.7
            sub_directory: 'wolf_whistle/'

          - action: 'forward'
            bounding_box_colour: [0,255,255]
            sensitivity: 0.7
            sub_directory: 'good_bad_ugly/'

          - action: 'backward'
            bounding_box_colour: [0,255,0]
            sensitivity: 0.7
            sub_directory: 'hill_slope/'

          - action: 'left'
            bounding_box_colour: [255,0,255]
            sensitivity: 0.7
            sub_directory: 'woody/'

          - action: 'right'
            bounding_box_colour: [255,255,0]
            sensitivity: 0.7
            sub_directory: '4_wide_invert_siren/'
